name: "Build releases"

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_DEV_DEBUG: 0
  CARGO_HUSKY_DONT_INSTALL_HOOKS: true
  COMPLETION_DIR: "target/tmp/moonbois/completion/"
  MANPAGE_DIR: "target/tmp/moonbois/manpage/"

permissions:
  id-token: write
  contents: write
  attestations: write

jobs: 
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  build-binaries:
    name: "Build binaries"
    runs-on: ${{ matrix.info.os }}
    needs: release
    continue-on-error: true
    container: ${{ matrix.info.container }}
    timeout-minutes: 12
    strategy:
      fail-fast: false
      matrix:
        info:
          # ======= Supported targets =======
          # Linux (x86-64, x86, aarch64)
          - {
              os: "ubuntu-22.04",
              target: "x86_64-unknown-linux-gnu",
              cross: false,
              generate-other-artifacts: true,
            }
          - {
              os: "ubuntu-22.04",
              target: "i686-unknown-linux-gnu",
              cross: true,
            }
          - {
              os: "ubuntu-22.04",
              target: "x86_64-unknown-linux-musl",
              cross: true,
            }
          - {
              os: "ubuntu-22.04",
              target: "i686-unknown-linux-musl",
              cross: true,
            }
          - {
              os: "ubuntu-22.04",
              target: "aarch64-unknown-linux-gnu",
              cross: true,
            }
          - {
              os: "ubuntu-22.04",
              target: "aarch64-unknown-linux-musl",
              cross: true,
            }

          # macOS (x86-64 and aarch64)
          - { os: "macos-13", target: "x86_64-apple-darwin", cross: false }
          - { os: "macos-14", target: "aarch64-apple-darwin", cross: false }

          # Windows (x86-64, x86)
          - {
              os: "windows-latest",
              target: "x86_64-pc-windows-msvc",
              cross: false,
            }
          - { 
              os: "windows-latest", 
              target: "i686-pc-windows-msvc", 
              cross: false 
            }
          - {
              os: "windows-latest",
              target: "x86_64-pc-windows-gnu",
              cross: false,
            }
    steps:
      - name: 
        - if: runner.os == 'windows-latest'
          run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          run: vcpkg install openssl:x64-windows-static-md
          
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 1

      - name: Set up Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.info.target }}

      - name: Build linux & macos
        if: ${{ !contains(matrix.platform.os, 'windows') }}
        uses: ClementTsang/cargo-action@v0.0.5
        with:
          command: build
          args: --release --verbose --target=${{ matrix.info.target }}
          use-cross: ${{ matrix.info.cross }}
          cross-version: 0.2.5

      - name: Build windows
        if: ${{ contains(matrix.platform.os, 'windows') }}
        shell: powershell
        run: cargo build --release --target ${{ matrix.info.target }}

      - name: Package release (Windows)
        if: matrix.info.os == 'windows-latest'
        shell: bash
        run: |
          cp target/${{ matrix.info.target }}/release/cli.exe moonbois_${{ matrix.info.target }}.exe
          echo "ASSET=moonbois_${{ matrix.info.target }}.exe" >> $GITHUB_ENV

      - name: Package release (Linux and macOS)
        if: matrix.info.os != 'windows-latest'
        shell: bash 
        run: |
          cp target/${{ matrix.info.target }}/release/cli moonbois_${{ matrix.info.target }}
          echo "ASSET=moonbois_${{ matrix.info.target }}" >> $GITHUB_ENV

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ASSET }}
          asset_name: ${{ env.ASSET }}
          tag: ${{ github.ref_name }}
      
