name: Rust

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

  publish:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup rust/openssl
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build binary
        run: cargo build --release
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/cli
          asset_name: ubuntu_linux_moonbois_cli
          tag: ${{ github.ref_name }}
